# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set([('from_user', 'to_user')]),
        ),
    ]
