# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('i', 'image'), ('v', 'video'), ('u', 'update'), ('t', 'text'), ('a', 'article')], db_index=True, max_length=1)),
                ('message', models.TextField()),
                ('source', models.URLField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('public', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
