# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='friend',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
